// temporary file to collect client/server messages

var errors = [
	// unknown
	['ERROR_UNKNOWN',     'uknown', 'Unknown error.'],
	['ERROR_UNKNOWN_CMD', '',       'Unknown command.'],
	// conf/connection
	['ERROR_CONF',         '',         'Invalid backend configuration.'],
	['ERROR_CONF_NO_JSON', '',         'PHP JSON module not installed.'],
	['ERROR_CONF_NO_VOL',  '',         'There are no one readable volumes available.'],
	['ERROR_INV_PARAMS',   '',         'Invalid parameters for command "$1".'],
	['',                   'access',   'Backend access denied.'],
	['',                   'backend',  'Backend not found.'],
	['',                   'jqui',     'Invalid jQuery UI configuration. Check selectable, draggable, draggable and dialog components included.'],
	['',                   'node',     'elFinder required DOM Element to be created.'],
	['',                   'url',      'Invalid elFinder configuration! You have to set URL option.'],							
	['',                   'connect',  'Unable to connect to backend.'],
	['',                   'abort',    'Connection to backend aborted.'],
	['',                   'timeout',  'Connection to backend timeout.'],
	['',                   'response', 'Invalid backend response.'],
	['',                   'json',     'Data is not JSON.'],
	['',                   'empty',    'Data is empty.'],
	['',                   'nocmd',    'Backend request required command name.'],
	
	['ERROR_OPEN',             'open',    'Unable to open "$1".'],
	['ERROR_DIR_NOT_FOUND',    '',        'Folder not found.'],
	['ERROR_FILE_NOT_FOUND',   '',        'File not found.'],
	['ERROR_TRGDIR_NOT_FOUND', '',        'Target folder "$1" not found.'],
	['ERROR_NOT_DIR',          'notdir',  'Object is not a folder.'],
	['ERROR_NOT_FILE',         'notfile', 'Object is not a file.'],
	['ERROR_NOT_READ',         'read',    'Unable to read "$1".'],
	['ERROR_NOT_WRITE',        'write',   'Unable to write into "$1".'],
	['ERROR_PERM_DENIED',      'denied',  'Permission denied.'],
	['ERROR_LOCKED',           'locked',  '"$1" is locked and can not be renamed or removed.'],
	['ERROR_EXISTS',           'exists',  'File named "$1" already exists in this location.'],
	['ERROR_INVALID_NAME',     'name',    '"$1" is not valid file name.'],
	['ERROR_MKDIR',            '',        'Unable to create folder "$1".'],
	['ERROR_MKFILE',           '',        'Unable to create file "$1".'],
	['ERROR_RENAME',           '',        'Unable to rename "$1".'],
	['ERROR_COPY',             '',        'Unable to copy "$1".'],
	['ERROR_MOVE',             '',        'Unable to move "$1".'],
	['ERROR_COPY_FILES',       '',        'Unable to copy files.'],
	['ERROR_MOVE_FILES',       '',        'Unable to move files.'],
	['ERROR_COPY_FROM',        '',        'Copy files from volume "$1" not allowed.'],
	['ERROR_COPY_TO',          '',        'Copy files to volume "$1" not allowed.'],
	['ERROR_COPY_ITSELF',      '',        'Unable to copy "$1" into itself.'],
	['ERROR_RM',               '',        'Unable to remove "$1".'],
	['ERROR_RM_FILES',         '',        'Unable to remove files.'],
	['ERROR_UPLOAD',           '',        'Unable to upload "$1".'],
	['ERROR_UPLOAD_FILES',     '',        'Unable to upload files.'],
	['ERROR_UPLOAD_SIZE',      '',        'Data exceeds the maximum allowed size.'],
	['ERROR_UPLOAD_NO_FILES',  '',        'There are no uploaded files was found.'],
	['ERROR_MIME',             '',        'File "$1" has not allowed file type.'],
]

